language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
  
script:
  - npm run coverage

services:
- postgresql
addons:
  postgresql: '9'
  apt:
    packages:
      - postgresql-9
      - postgresql-client-9
env:
  global:
    - PGPORT=5432
    - DATABASE_URL_TEST=postgres://postgres@127.0.0.1:5432/safehaven
before_script:
 - npm install
 - sudo service postgresql restart
 - psql -c 'create database safehaven;' -U postgres
