language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
  

script:
  - npm run test

after_success:
  - npm run coverage

services:
- postgresql

before_script:
 - psql -c 'create database safehaven;' -U postgres
