language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
  
script:
  - npm run coverage

services:
- postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_script:
 - npm install
 - psql -c 'create database safehaven;' -U postgres
