language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
  
script:
  - npm run coverage
  - npm run migrate-test

services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_script:
 - npm install
 - psql -c 'create database safehaven;' -U postgres
